version: '3.8'

services:
  crawl4rag:
    labels:
      - com.centurylinklabs.watchtower.enable=false
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawl4rag
    ports:
      - "${PORT:-8051}:${PORT:-8051}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=crawl4rag-db
      - NEO4J_URI=bolt://crawl4rag-neo4j:7687
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEO4J_PASSWORD_FILE=/run/secrets/neo4j_password
    secrets:
      - postgres_user
      - postgres_password
      - neo4j_password
    depends_on:
      crawl4rag-db:
        condition: service_healthy
      crawl4rag-neo4j:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-8051}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  crawl4rag-db:
    image: pgvector/pgvector:pg16
    container_name: crawl4rag-db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=${POSTGRES_DB:-crawl4rag}
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - crawl4rag_db_data:/var/lib/postgresql/data
      - ./crawled_pages.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5332:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d ${POSTGRES_DB:-crawl4rag}"]
      interval: 10s
      timeout: 5s
      retries: 5

  crawl4rag-neo4j:
    image: neo4j:5
    container_name: crawl4rag-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    secrets:
      - neo4j_password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - crawl4rag_neo4j_data:/data

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  neo4j_password:
    file: ./secrets/neo4j_password.txt

volumes:
  crawl4rag_db_data:
    driver: local
  crawl4rag_neo4j_data:
    driver: local